name: Build and Publish to PyPI

# This will trigger the workflow when a tag is pushed
on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    needs: ci-pipeline  # This ensures the build job runs after ci-pipeline job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install PDM
        run: |
          pip install pdm

      - name: Install dependencies
        run: |
          pdm install

      - name: Build the package
        run: |
          pdm build  # Build the package (sdist and wheel)

      - name: Publish to PyPI
        run: |
          pdm publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}  # Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}  # Ensure you have set the token as a secret
