name: CI Pipeline

on:
  pull_request:
    branches:
      - main

env:
  project_name: semantic_framework # Define a global variable for the project name
  python_version: '3.10.12' 

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }} 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # This installs the dependencies from requirements.txt file

      - name: Run pylint
        run: |
          pylint ${{ env.project_name }} --max-line-length=88

      # - name: Run mypy
      #  run: |
      #    mypy ${{ env.project_name }}

      - name: Run black
        run: |
          black --check ${{ env.project_name }}

  test:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # This installs the dependencies from requirements.txt file

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q