name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  project_name: semantiva # Define a global variable for the project name
  python_version: '3.10.12'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Install PDM
        run: |
          pip install pdm

      - name: Install dependencies using PDM
        run: |
          pdm install

      - name: Run pylint
        run: |
          pdm run pylint ${{ env.project_name }} --fail-under=7.5

      - name: Run black
        run: |
          pdm run black --check ${{ env.project_name }}

  test:
    runs-on: ubuntu-latest
    needs: linting  # Ensure that the test job runs after linting job passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Install PDM
        run: |
          pip install pdm

      - name: Install dependencies using PDM
        run: |
          pdm install

      - name: Run pytest
        run: |
          PYTHONPATH=. pdm run pytest --maxfail=1 --disable-warnings -q